### PR TITLE
fix windows-latest actually running on ubuntu-latest

### PR DESCRIPTION
**Pull request by xflr6**
- follow-up c086b549da3c5bdc2c7b65976d8f39d15247eec7

### CODE REVIEW

**Comment by xrotwang** [comment]
Whatever is going on here, you sure know more about github actions than me now :)

**Comment by xflr6** [comment]
Hehe :)  AFAIR, Travis would run the tests with the new config in a branch that changes it, trying to get them to run here, no luck so far, will say explicitly when this looks ready (might need to set back and forth from draft more times).

**Comment by xflr6** [comment]
Okay, this should be good to go now, PTAL.

**Comment by xflr6** [comment]
Actually let me merge this so we can enjoy Windows testing in #45.

AFAIU actions allows to persists artifacts produced by the tests, so we could use this e.g. to make the the `treedb` results available and potentially to build and doploy all of glottolog by repository actions such as tagging.

**Pull request merged**
