### PR TITLE
render countries as alpha_2 only and allow minimal format for reading

### PR DESCRIPTION
**Pull request by xflr6**
- see glottolog/glottolog#635

### CODE REVIEW

**Comment by xflr6** [comment]
glottolog/glottolog#636 is in: merge this and create a new release?

**Comment by xrotwang** [comment]
Is this backwards compatible?

**Comment by xflr6** [comment]
Yes (changing the output format and epanding the input format, see also `test_Country_from_text`).

Actually, the released version is already quite permissive to allow e.g. `'spamID)spam'`, so we could reduce the change further, but I was not sure if we might want to make it a bit stricter at some point so I have added matching only `'ID'` separately, WDYT?

**Comment by xrotwang** [comment]
Feel free to merge. I can make a release tomorrow.

**Comment by xflr6** [comment]
Thanks, closed.

**Comment by xrotwang** [comment]
released in https://pypi.org/project/pyglottolog/3.3.0/

**Pull request merged**
